---
- name: Configure VYOS lab
  hosts: router1
  gather_facts: no

  tasks:
  - name: Element only in bgp.networks['network']
    debug:
      msg: "{{ item }}"
    loop: "{{ bgp.networks | map(attribute='network') }}"

  - name: Look for elements missing in first variable
    debug:
      msg: "{{ element.network }}{{ element.mask }}"
    loop: "{{ bgp.networks  }}"
    loop_control:
      loop_var: element

  - name: Using lookup for dict
    debug:
      msg: "{{ item }}"
    lookup('dict', bgp)