---
- name: Configure VYOS lab
  hosts: all
  gather_facts: no

  tasks:

  - name: Configure loopback
    vyos_config: 
      src: templates/loopback.j2

  - name: Configure BGP 
    vyos_config:
      src: "templates/bgp.j2"

  